image: cprov/stoq:latest

services:
  - postgres:9.5

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # Fetch utils/ submodule
  GIT_SUBMODULE_STRATEGY: recursive
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ""
  STOQLIB_TEST_HOSTNAME: "postgres"
  STOQLIB_TEST_DBNAME: "test"
  STOQLIB_TEST_USERNAME: "test"
  STOQLIB_TEST_PASSWORD: ""

before_script:
  - python3 -V  # Print out python version for debugging
  # Missing devel dependency
  - apt update -q
  - locale-gen pt_BR.UTF-8
  - locale-gen en_US.UTF-8
  - apt install build-essential python3.5-dev -y
  - virtualenv -p python3 --system-site-packages venv
  - source venv/bin/activate
  - pip3 uninstall setuptools -y
  - pip3 install -U setuptools pip
  - pip3 install https://launchpad.net/~stoq-maintainers/+archive/ubuntu/unstable/+sourcefiles/storm/0.20.0.100-2~py3-1bionic/storm_0.20.0.100-2~py3-1bionic.tar.gz
  - git clone https://github.com/stoq/stoq.git
  - pip3 install -e stoq --no-deps
  - pip3 install -Ur requirements-test.txt
  - ln -s $PWD/venv/bin/pyflakes $PWD/venv/bin/pyflakes3
  
test:
  script:
    - ./runtests.py stoqserver/lib/test
