image: cprov/stoq:candidate

services:
  - postgres:9.5

variables:
  # Fetch utils/ submodule
  GIT_SUBMODULE_STRATEGY: recursive
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ""
  STOQLIB_TEST_HOSTNAME: "postgres"
  STOQLIB_TEST_DBNAME: "test"
  STOQLIB_TEST_USERNAME: "test"
  STOQLIB_TEST_PASSWORD: ""

stages:
  - test
  - build

before_script:
  # Install stoqlib from master.
  - git clone https://github.com/stoq/stoq.git
  - easy_install3 pip
  - pip install -e stoq --no-deps
  - pip install -r requirements-test.txt
  # Install tools to create debian packages
  - apt update
  - apt --yes install devscripts debhelper python3-all

test:
  stage: test
  script:
    - ./runtests.py stoqserver/lib/test
    - pytest -v tests

generate_deb:
  stage: build
  script:
    - rm -rf dist
    - make deb

  artifacts:
    paths:
      - dist/*.deb

  only:
  - master
