image: cprov/stoq:candidate

services:
  - postgres:9.5

variables:
  # Fetch utils/ submodule
  GIT_SUBMODULE_STRATEGY: recursive
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ""
  STOQLIB_TEST_HOSTNAME: "postgres"
  STOQLIB_TEST_DBNAME: "test"
  STOQLIB_TEST_USERNAME: "test"
  STOQLIB_TEST_PASSWORD: ""

stages:
  - test
  - build

before_script:
  # Install stoqlib from master.
  - apt update
  - apt --yes install libcairo2-dev libgirepository1.0-dev python3-pip python3-virtualenv libpq-dev swig
  - git clone https://github.com/stoq/stoq.git --depth 1
  - python3 -m venv env
  - source env/bin/activate
  - python --version
  - which python
  - pip --version
  - pip install -U kiwi-gtk setuptools pip wheel
  - pip install -e stoq
  - pip install https://github.com/stoq/stoqdrivers/archive/master.zip
  - pip install -r requirements-test.txt
  - pip freeze

test:
  stage: test
  script:
    - make coverage

.create_deb:
  stage: build
  script:
    # Install tools to create debian packages
    - apt update
    - apt --yes install devscripts debhelper python3-all
    - rm -rf dist
    - make deb
  artifacts:
    paths:
      - dist/*.deb

create_deb_master:
  extends: .create_deb
  only:
    - master

create_deb_manual:
  extends: .create_deb
  when: manual
